export const defaultSchema = [
  {
    "attr": 0,
    "canTrigger": true,
    "cloudlessEditPermission": true,
    "cloudlessEnable": false,
    "cloudlessShow": true,
    "code": "total_duration",
    "defaultRecommend": false,
    "editPermission": false,
    "executable": true,
    "extContent": "",
    "hasDpProtocol": false,
    "id": 101,
    "mode": "rw",
    "name": "专注时长",
    "passiveEditPermission": true,
    "passiveEnable": false,
    "passiveShow": true,
    "property": {
      "type": "enum",
      "range": [
        "min_15",
        "min_30",
        "min_45",
        "min_60",
        "min_90"
      ]
    },
    "required": false,
    "routeEditPermission": false,
    "routeShow": false,
    "routeType": 0,
    "selected": true,
    "standarded": 0,
    "subType": "enum",
    "triggerEditPermission": true,
    "triggerEnable": false,
    "triggerShow": true,
    "type": "obj"
  },
  {
    "attr": 0,
    "canTrigger": true,
    "cloudlessEditPermission": true,
    "cloudlessEnable": false,
    "cloudlessShow": true,
    "code": "piece_count",
    "defaultRecommend": false,
    "editPermission": false,
    "executable": true,
    "extContent": "",
    "hasDpProtocol": false,
    "id": 102,
    "mode": "rw",
    "name": "图块数量",
    "passiveEditPermission": true,
    "passiveEnable": false,
    "passiveShow": true,
    "property": {
      "type": "enum",
      "range": [
        "piece_1",
        "piece_3",
        "piece_5",
        "piece_6",
        "piece_9"
      ]
    },
    "required": false,
    "routeEditPermission": false,
    "routeShow": false,
    "routeType": 0,
    "selected": true,
    "standarded": 0,
    "subType": "enum",
    "triggerEditPermission": true,
    "triggerEnable": false,
    "triggerShow": true,
    "type": "obj"
  },
  {
    "attr": 0,
    "canTrigger": true,
    "cloudlessEditPermission": true,
    "cloudlessEnable": false,
    "cloudlessShow": true,
    "code": "current_piece",
    "defaultRecommend": false,
    "editPermission": false,
    "executable": true,
    "extContent": "",
    "hasDpProtocol": false,
    "id": 103,
    "mode": "ro",
    "name": "已消除图块数",
    "passiveEditPermission": true,
    "passiveEnable": false,
    "passiveShow": true,
    "property": {
      "max": 9,
      "min": 0,
      "scale": 0,
      "step": 1,
      "type": "value",
      "unit": "块"
    },
    "required": false,
    "routeEditPermission": false,
    "routeShow": false,
    "routeType": 0,
    "selected": true,
    "standarded": 0,
    "subType": "value",
    "triggerEditPermission": true,
    "triggerEnable": false,
    "triggerShow": true,
    "type": "obj"
  },
  {
    "attr": 0,
    "canTrigger": true,
    "cloudlessEditPermission": true,
    "cloudlessEnable": false,
    "cloudlessShow": true,
    "code": "timer_status",
    "defaultRecommend": false,
    "editPermission": false,
    "executable": true,
    "extContent": "",
    "hasDpProtocol": false,
    "id": 104,
    "mode": "rw",
    "name": "专注状态",
    "passiveEditPermission": true,
    "passiveEnable": false,
    "passiveShow": true,
    "property": {
      "type": "enum",
      "range": [
        "idle",
        "running",
        "completed"
      ]
    },
    "required": false,
    "routeEditPermission": false,
    "routeShow": false,
    "routeType": 0,
    "selected": true,
    "standarded": 0,
    "subType": "enum",
    "triggerEditPermission": true,
    "triggerEnable": false,
    "triggerShow": true,
    "type": "obj"
  },
  {
    "attr": 0,
    "canTrigger": true,
    "cloudlessEditPermission": true,
    "cloudlessEnable": false,
    "cloudlessShow": true,
    "code": "theme",
    "defaultRecommend": false,
    "editPermission": false,
    "executable": true,
    "extContent": "",
    "hasDpProtocol": false,
    "id": 105,
    "mode": "rw",
    "name": "显示主题",
    "passiveEditPermission": true,
    "passiveEnable": false,
    "passiveShow": true,
    "property": {
      "type": "enum",
      "range": [
        "pizza",
        "stars",
        "miku",
        "custom"
      ]
    },
    "required": false,
    "routeEditPermission": false,
    "routeShow": false,
    "routeType": 0,
    "selected": true,
    "standarded": 0,
    "subType": "enum",
    "triggerEditPermission": true,
    "triggerEnable": false,
    "triggerShow": true,
    "type": "obj"
  },
  {
    "attr": 0,
    "canTrigger": true,
    "cloudlessEditPermission": true,
    "cloudlessEnable": false,
    "cloudlessShow": true,
    "code": "custom_image",
    "defaultRecommend": false,
    "editPermission": false,
    "executable": true,
    "extContent": "",
    "hasDpProtocol": false,
    "id": 106,
    "mode": "wr",
    "name": "自定义图片数据",
    "passiveEditPermission": true,
    "passiveEnable": false,
    "passiveShow": true,
    "property": {
      "maxlen": 128,
      "type": "raw"
    },
    "required": false,
    "routeEditPermission": false,
    "routeShow": false,
    "routeType": 0,
    "selected": true,
    "standarded": 0,
    "subType": "raw",
    "triggerEditPermission": true,
    "triggerEnable": false,
    "triggerShow": true,
    "type": "raw"
  },
  {
    "attr": 0,
    "canTrigger": true,
    "cloudlessEditPermission": true,
    "cloudlessEnable": false,
    "cloudlessShow": true,
    "code": "image_upload_status",
    "defaultRecommend": false,
    "editPermission": false,
    "executable": true,
    "extContent": "",
    "hasDpProtocol": false,
    "id": 107,
    "mode": "ro",
    "name": "自定义图片上传状态",
    "passiveEditPermission": true,
    "passiveEnable": false,
    "passiveShow": true,
    "property": {
      "type": "enum",
      "range": [
        "idle",
        "receiving",
        "ready",
        "error"
      ]
    },
    "required": false,
    "routeEditPermission": false,
    "routeShow": false,
    "routeType": 0,
    "selected": true,
    "standarded": 0,
    "subType": "enum",
    "triggerEditPermission": true,
    "triggerEnable": false,
    "triggerShow": true,
    "type": "obj"
  },
  {
    "attr": 0,
    "canTrigger": true,
    "cloudlessEditPermission": true,
    "cloudlessEnable": false,
    "cloudlessShow": true,
    "code": "image_upload_progress",
    "defaultRecommend": false,
    "editPermission": false,
    "executable": true,
    "extContent": "",
    "hasDpProtocol": false,
    "id": 108,
    "mode": "ro",
    "name": "图片上传进度",
    "passiveEditPermission": true,
    "passiveEnable": false,
    "passiveShow": true,
    "property": {
      "max": 100,
      "min": 0,
      "scale": 0,
      "step": 5,
      "type": "value",
      "unit": "%"
    },
    "required": false,
    "routeEditPermission": false,
    "routeShow": false,
    "routeType": 0,
    "selected": true,
    "standarded": 0,
    "subType": "value",
    "triggerEditPermission": true,
    "triggerEnable": false,
    "triggerShow": true,
    "type": "obj"
  }
] as const;
